### ISSUE TITLE
800epoch model weights

### ISSUE THREAD

**Issue by hhhhhpy** [MCG-NJU/AMD#1]
thanks for the great work! but the author seems only provide pre-trained model for 200 epochs for kinetics-400, which is inconsistent with the description(800 epoch) in the table. Can the author release the 800-ep version? Thanks a lot.
![屏幕截图 2024-07-25 163216](https://github.com/user-attachments/assets/5a348a23-ec07-4f84-a1fd-5f0801d252c1)

**Comment by JerryFlymi** [comment]
ref"We always count epochs as "effective epochs", i.e., how many times each raw video is sampled throughout training."

**Comment by JerryFlymi** [comment]
Thanks for the attention! The weight given is indeed for 800epoch. Sorry for the confusion, the 800epoch represents the number of “effective epochs” i.e., how many times each raw video is sampled throughout training. We set repeat aug=4, i.e. 200epochx4 repeat times=800 effective epochs.

**Comment by hhhhhpy** [comment]
Thanks for the reply.
